version: '3.7'

x-shared:
  &common
  NEO4J_AUTH: neo4j/foobar
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000
  NEO4J_dbms_memory_pagecache_size: "1500M" 
  NEO4J_dbms_memory_heap_initial__size: "1500M"

x-shared-core:
  &common-core
  <<: *common
  NEO4J_dbms_mode: CORE
  NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: 3

networks: 
  lan:

services:

  core1:
    image: neo4j:enterprise
    networks:
      - lan 
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      <<: *common-core
      NEO4J_causal__clustering_discovery__advertised__address: core1:5000 
      NEO4J_causal__clustering_transaction__advertised__address: core1:6000
      NEO4J_causal__clustering_raft__advertised__address: core1:7000
      NEO4J_dbms_default__advertised__address: core1

  core2:
    image: neo4j:enterprise
    networks:
      - lan
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      <<:  *common-core
      NEO4J_causal__clustering_discovery__advertised__address: core2:5000
      NEO4J_causal__clustering_transaction__advertised__address: core2:6000
      NEO4J_causal__clustering_raft__advertised__address: core2:7000
      NEO4J_dbms_default__advertised__address: core2

  core3:
    image: neo4j:enterprise
    networks:
      - lan
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      <<:  *common-core
      NEO4J_causal__clustering_discovery__advertised__address: core3:5000
      NEO4J_causal__clustering_transaction__advertised__address: core3:6000
      NEO4J_causal__clustering_raft__advertised__address: core3:7000
      NEO4J_dbms_default__advertised__address: core3

  readreplica1:
    image: neo4j:enterprise
    networks:
      - lan
    ports:
      - "7477:7474"
      - "7690:7687"
    environment:
      <<:  *common
      NEO4J_dbms_mode: READ_REPLICA
      NEO4J_causal__clustering_discovery__advertised__address: readreplica1:5000
      NEO4J_causal__clustering_transaction__advertised__address: readreplica1:6000
      NEO4J_causal__clustering_raft__advertised__address: readreplica1:7000
      NEO4J_dbms_default__advertised__address: readreplica1
      
  fabric:
    image: neo4j:enterprise
    networks:
      - lan
    ports:
      - "7478:7474"
      - "7691:7687"
    environment:
      NEO4J_AUTH: neo4j/foobar
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_mode: SINGLE
      NEO4J_dbms_memory_pagecache_size: "1500M" 
      NEO4J_dbms_memory_heap_initial__size: "1500M"
      NEO4J_dbms_default__database: fabric
      NEO4J_fabric_database_name: fabric
      NEO4J_fabric_graph_0_uri: "neo4j://core1:7687,neo4j://core2:7687,neo4j://core3:7687"
      NEO4J_fabric_graph_0_database: "neo4j"
      NEO4J_fabric_graph_0_name: graphA
      NEO4J_fabric_graph_1_uri: "neo4j://single1:7687"
      NEO4J_fabric_graph_1_database: "neo4j"
      NEO4J_fabric_graph_1_name: graphB
      
  single1:
    image: neo4j:enterprise
    networks:
      - lan
    ports:
      - "7479:7474"
      - "7692:7687"
    environment:
      NEO4J_AUTH: neo4j/foobar
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_mode: SINGLE
      NEO4J_dbms_memory_pagecache_size: "1500M" 
      NEO4J_dbms_memory_heap_initial__size: "1500M"
      
  jupyter:
    build: ./jupyter 
    ports:
      - "8888:8888"
    networks:
      - lan